name: Automated Tests

on:
  schedule:
    - cron: '0 * * * *'  # Se ejecuta cada hora
  push:
    branches: [ main ]  # Se ejecuta en cada push a main
  workflow_dispatch:   

env:
  NODE_VERSION: '22'
  NEXT_PUBLIC_API_URL: 'https://www.spiderswap.io/'
  SOLANA_RPC: 'https://ratty-wandie-fast-mainnet.helius-rpc.com/'
  NEXT_PUBLIC_SOLANA_RPC_HOST: 'https://ratty-wandie-fast-mainnet.helius-rpc.com/'

jobs:
  production-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Clean npm cache
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
    
    - name: Install dependencies
      run: |
        npm install
        npm install cypress@latest --save-dev
        npm install mocha@11.1.0 browser-stdout@1.3.1 glob@10.4.5 he@1.2.0 minimatch@5.1.6 serialize-javascript@6.0.2 workerpool@6.5.1 yargs@17.7.2 yargs-parser@21.1.1 yargs-unparser@2.0.0 randombytes@2.1.0 typescript@5.8.3 camelcase@6.3.0 decamelize@4.0.0 flat@5.0.2 is-plain-obj@2.1.0 minimatch@9.0.5 brace-expansion@2.0.1 cliui@8.0.1 --save-dev
    
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        install: false  # Skip installation since we already installed dependencies
        config: >-
          {
            "baseUrl": "https://www.spiderswap.io",
            "video": false,
            "defaultCommandTimeout": 30000,
            "experimentalStudio": false,
            "reporter": "mochawesome",
            "reporterOptions": {
              "reportDir": "cypress/reports",
              "overwrite": false,
              "html": false,
              "json": true
            }
          }
      env:
        CYPRESS_BASE_URL: 'https://www.spiderswap.io'
        CYPRESS_SOLANA_RPC: ${{ env.SOLANA_RPC }}
        CYPRESS_WALLET_SEED: ${{ secrets.WALLET_SEED }}
        CYPRESS_WALLET_ADDR: ${{ secrets.WALLET_ADDR }}
        CYPRESS_WALLET_SHORT_ADDR: ${{ secrets.WALLET_SHORT_ADDR }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-test-results
        path: cypress/reports/
        retention-days: 30

    - name: Send results to Discord
      if: always()
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      run: node bot/report_bot.mjs

