name: Automated Tests
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches: [ main ]  # Runs on each push to main
  workflow_dispatch:  # Allows manual triggering
  
env:
  NODE_VERSION: '22'
  NEXT_PUBLIC_API_URL: 'https://www.spiderswap.io/'
  SOLANA_RPC: 'https://ratty-wandie-fast-mainnet.helius-rpc.com/'
  NEXT_PUBLIC_SOLANA_RPC_HOST: 'https://ratty-wandie-fast-mainnet.helius-rpc.com/'

jobs:
  production-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
    - uses: actions/checkout@v4
   
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
   
    - name: Install dependencies
      run: npm ci
   
    # Identifica todos los archivos de test disponibles
    - name: Find test files
      id: find-tests
      run: |
        echo "test_files=$(find cypress/e2e -name "*.cy.{js,jsx,ts,tsx}" -type f | tr '\n' ' ')" >> $GITHUB_OUTPUT
        
    # Ejecuta cada test uno por uno de forma secuencial, continúa al siguiente si hay fallos
    - name: Run Cypress tests sequentially
      uses: cypress-io/github-action@v6
      continue-on-error: true  # Permite continuar incluso si un test falla
      with:
        browser: firefox
        # Ejecuta cada archivo de test individualmente
        spec: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}'
        config: |
          {
            "baseUrl": "https://www.spiderswap.io",
            "video": false,
            "defaultCommandTimeout": 30000,
            "experimentalStudio": false,
            "reporter": "mochawesome",
            "reporterOptions": {
              "reportDir": "cypress/reports",
              "overwrite": false,
              "html": false,
              "json": true
            }
          }
      env:
        CYPRESS_BASE_URL: 'https://www.spiderswap.io'
        CYPRESS_SOLANA_RPC: ${{ env.SOLANA_RPC }}
        CYPRESS_WALLET_SEED: ${{ secrets.WALLET_SEED }}
        CYPRESS_WALLET_ADDR: ${{ secrets.WALLET_ADDR }}
        CYPRESS_WALLET_SHORT_ADDR: ${{ secrets.WALLET_SHORT_ADDR }}
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-test-results
        path: cypress/reports/
        retention-days: 30
        if-no-files-found: warn
        
    - name: Send results to Discord
      if: always()
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      run: node bot/report_bot.mjs